---

- name: Generate password hash for admin user
  connection: local
  command: "openssl passwd -1 {{ icingaweb2_admin_pass }}"
  register: icingaweb2_admin_hash

- name: Create temp file on remote host
  shell: mktemp
  register: icingaweb2_sql_temp

- name: Generate SQL statements
  template: src=insert_admin.sql.j2 dest={{ icingaweb2_sql_temp.stdout }}

- name: Run SQL statements
  mysql_db: state=import db={{ icingaweb2_web_db }} target={{ icingaweb2_sql_temp.stdout }}

- name: Remove temp file on remote host
  file: name={{ icingaweb2_sql_temp.stdout }} state=absent

